
@HOST_NAME = http://localhost:8000
@PREDICTION_PATH = calc
@STATUS_PATH = status
@TRAIN_PATH = train
@DATA_PATH = data
@REVERT_PATH = revert
@ACCURACY_ENDPOINT = accuracy

### Get irrelevant prediction
POST {{HOST_NAME}}/{{PREDICTION_PATH}}
Content-Type: application/json

{
  "text": "Life is life."
}

### Get negative prediction
POST {{HOST_NAME}}/{{PREDICTION_PATH}}
Content-Type: application/json

{
  "text": "Life is misery."
}

### Get neutral prediction
POST {{HOST_NAME}}/{{PREDICTION_PATH}}
Content-Type: application/json

{
  "text": "Today I feel average."
}


### Get positive prediction
POST {{HOST_NAME}}/{{PREDICTION_PATH}}
Content-Type: application/json

{
  "text": "What a beautiful day to code in python. This is definitely not sarcasm and I love this language so much"
}

### Check the status of the model
GET {{HOST_NAME}}/{{STATUS_PATH}}

### Trigger a re-render of the model
POST {{HOST_NAME}}/{{TRAIN_PATH}}

### Switch the models
GET {{HOST_NAME}}/{{REVERT_PATH}}

### Get the accuracy of models
GET {{HOST_NAME}}/{{ACCURACY_ENDPOINT}}