
@HOST_NAME = http://localhost:8000
@PREDICTION_PATH = calc
@STATUS_PATH = status
@TRAIN_PATH = train
@DATA_PATH = data

### Get irrelevant prediction
POST {{HOST_NAME}}/{{PREDICTION_PATH}}
Content-Type: application/json

{
  "text": "Life is misery. It is truly a marvel how one hasn't ended it all."
}

### Get negative prediction
POST {{HOST_NAME}}/{{PREDICTION_PATH}}
Content-Type: application/json

{
  "text": "Life is misery."
}

### Get neutral prediction
POST {{HOST_NAME}}/{{PREDICTION_PATH}}
Content-Type: application/json

{
  "text": "Today I feel average."
}


### Get positive prediction
POST {{HOST_NAME}}/{{PREDICTION_PATH}}
Content-Type: application/json

{
  "text": "What a beautiful day to code in python. This is definitely not sarcasm and I love this language so much"
}

### Check the status of the model
GET {{HOST_NAME}}/{{STATUS_PATH}}

### Trigger a re-render of the model
POST {{HOST_NAME}}/{{TRAIN_PATH}}

### Get data points that include the selected text
GET {{HOST_NAME}}/{{DATA_PATH}}?text=kill

### Add data point
POST {{HOST_NAME}}/{{DATA_PATH}}
Content-Type: application/json

{
  "text": "Life is good",
  "sentiment": "Positive"
}

### Delete data point with a specific ID
DELETE {{HOST_NAME}}/{{DATA_PATH}}?id=5
