FROM python:3.7-alpine

# Set up working directory
WORKDIR /app 
COPY /apps /app

RUN pip3 install -r requirements.txt --no-cache-dir

EXPOSE 8000
ENTRYPOINT ["python3"] 
CMD ["manage.py", "runserver", "0.0.0.0:8000"]