version: "3.9"

services:
  web:
    container_name: web
    image: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
  api:
    container_name: api
    image: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"