# Continue using the Alpine base image
FROM python:3.8-alpine

WORKDIR /app

# Install build dependencies for scipy
RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev g++ gfortran make

# Copy just the requirements.txt first to leverage Docker cache
COPY ./apps/requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY /apps /app


EXPOSE 8000
ENTRYPOINT ["python3"] 
CMD ["manage.py", "runserver", "0.0.0.0:8000"]