FROM node:18.16.0

# Set up working directory
WORKDIR /app

COPY /apps/web /app/web
COPY /apps/admin /app/admin

# Build Admin dashboard
RUN cd ./admin && npm install && npm run build
RUN cd ./web && npm install && npm run build

# Expose port 5000 for the Express server
EXPOSE 5000

WORKDIR /app/web
CMD ["npm", "run", "start"]